In [8]:
import pandas as pd 

titanic_train =pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv%22, sep='\t'")

InvalidURL: URL can't contain control characters. "/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv%22, sep='\t'" (found at least ' ')

In [12]:
titanic = pd.read_csv('./titanic.csv')

In [13]:
dy = titanic.dtypes

In [14]:
dy[0:4]

PassengerId     int64
Survived        int64
Pclass          int64
Name           object
dtype: object

In [17]:
dy[0:100:2]

PassengerId     int64
Pclass          int64
Sex            object
SibSp           int64
Ticket         object
Cabin          object
dtype: object

In [18]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [21]:
titanic['Age'][10:100]

10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
      ... 
95     NaN
96    71.0
97    23.0
98    34.0
99    34.0
Name: Age, Length: 90, dtype: float64

In [22]:
titanic['Age'][::-1]

890    32.0
889    26.0
888     NaN
887    19.0
886    27.0
       ... 
4      35.0
3      35.0
2      26.0
1      38.0
0      22.0
Name: Age, Length: 891, dtype: float64

In [23]:
titanic['Age'][-1]

KeyError: -1

In [24]:
titanic['Age'][::2]

0      22.0
2      26.0
4      35.0
6      54.0
8      27.0
       ... 
882    22.0
884    25.0
886    27.0
888     NaN
890    32.0
Name: Age, Length: 446, dtype: float64

In [25]:
list(titanic['Age'][::2])

[22.0,
 26.0,
 35.0,
 54.0,
 27.0,
 4.0,
 20.0,
 14.0,
 2.0,
 31.0,
 35.0,
 15.0,
 8.0,
 nan,
 nan,
 40.0,
 nan,
 28.0,
 nan,
 18.0,
 40.0,
 nan,
 19.0,
 nan,
 nan,
 7.0,
 49.0,
 65.0,
 21.0,
 5.0,
 22.0,
 45.0,
 nan,
 29.0,
 17.0,
 32.0,
 21.0,
 32.0,
 nan,
 0.83,
 22.0,
 nan,
 17.0,
 16.0,
 23.0,
 29.0,
 46.0,
 59.0,
 71.0,
 34.0,
 28.0,
 21.0,
 37.0,
 21.0,
 38.0,
 47.0,
 22.0,
 17.0,
 70.5,
 24.0,
 21.0,
 32.5,
 54.0,
 nan,
 nan,
 33.0,
 47.0,
 25.0,
 19.0,
 16.0,
 nan,
 24.0,
 18.0,
 27.0,
 36.5,
 51.0,
 55.5,
 nan,
 16.0,
 nan,
 44.0,
 26.0,
 1.0,
 nan,
 nan,
 61.0,
 1.0,
 56.0,
 nan,
 30.0,
 nan,
 9.0,
 4.0,
 nan,
 40.0,
 32.0,
 19.0,
 44.0,
 nan,
 nan,
 28.0,
 34.0,
 18.0,
 32.0,
 16.0,
 24.0,
 22.0,
 nan,
 27.0,
 32.0,
 16.0,
 51.0,
 38.0,
 19.0,
 18.0,
 35.0,
 59.0,
 24.0,
 44.0,
 19.0,
 nan,
 29.0,
 30.0,
 25.0,
 37.0,
 nan,
 62.0,
 41.0,
 nan,
 35.0,
 nan,
 52.0,
 nan,
 16.0,
 58.0,
 nan,
 41.0,
 nan,
 45.0,
 7.0,
 65.0,
 16.0,
 nan,
 30.0,
 42.0,
 26.0,
 36.0,
 24.0,
 23.5

In [26]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [27]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [28]:
titanic.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [29]:
titanic.dtypes[titanic.dtypes == 'object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [30]:
titanic.dtypes[titanic.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [31]:
titanic[titanic.dtypes[titanic.dtypes == 'object'].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [32]:
type(titanic[titanic.dtypes[titanic.dtypes == 'object'].index])

pandas.core.frame.DataFrame

In [33]:
titanic_cat = titanic[titanic.dtypes[titanic.dtypes == 'object'].index]

In [34]:
titanic_cat.describe()

Name   Sex    Ticket        Cabin Embarked
count                               891   891       891          204      889
unique                              891     2       681          147        3
top     Brocklebank, Mr. William Alfred  male  CA. 2343  C23 C25 C27        S
freq                                  1   577         7            4      644

In [35]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [36]:
titanic['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [37]:
titanic['Name','Fare']

KeyError: ('Name', 'Fare')

In [38]:
titanic[['Name','Fare']]

Name     Fare
0                              Braund, Mr. Owen Harris   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                               Heikkinen, Miss. Laina   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                             Allen, Mr. William Henry   8.0500
..                                                 ...      ...
886                              Montvila, Rev. Juozas  13.0000
887                       Graham, Miss. Margaret Edith  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"  23.4500
889                              Behr, Mr. Karl Howell  30.0000
890                                Dooley, Mr. Patrick   7.7500

[891 rows x 2 columns]

In [39]:
type(titanic[['Name','Fare']])

pandas.core.frame.DataFrame

In [40]:
titanic['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [41]:
titanic['Age'].isnull()== True    

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [42]:
import numpy as np

In [43]:
np.where(titanic['Age'].isnull()== True)#gives indexes of null values entries

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [44]:
titanic[titanic['Age'].isnull()== True]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [45]:
titanic_age_null =np.where(titanic['Age'].isnull()== True)

In [46]:
titanic[['Name','Pclass']]

Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
888           Johnston, Miss. Catherine Helen "Carrie"       3
889                              Behr, Mr. Karl Howell       1
890                                Dooley, Mr. Patrick       3

[891 rows x 2 columns]

In [47]:
titanic.iloc[titanic_age_null] ##get df where the col age has null values

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [50]:
titanic.iloc[5]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [51]:
titanic.iloc[[1,2,3,4,6]]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
6      0             17463  51.8625   E46        S

In [56]:
titanic.iloc[np.where(titanic['Fare'] == max(titanic['Fare']))]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [57]:
titanic['new_col'] = 'sudh'

In [58]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked new_col  
0        0         A/5 21171   7.2500   NaN        S    sudh  
1        0          PC 17599  71.2833   C85        C    sudh  
2        0  STON/O2. 3101282   7.9250   NaN        S    sudh  
3        0            113803  53.1000  C123        S    sudh  
4        0            373450   8.0500   NaN        S    sudh  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S    sudh  
887      0            112053  30.0000   B42        S    sudh  
888      2        W./C. 6607  23.4500   NaN        S    sudh  
889      0            111369  30.0000  C148        C    sudh  
890      0            370376   7.7500   NaN        Q    sudh  

[891 rows x 13 columns]

In [59]:
l = [1,2,3,4,5]

In [60]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [61]:
d = {'key':'sudh','title':'kumar','mail':'aymane1000live.fr'}

In [63]:
pd.DataFrame(d,index=['key','title','mail'])

key  title               mail
key    sudh  kumar  aymane1000live.fr
title  sudh  kumar  aymane1000live.fr
mail   sudh  kumar  aymane1000live.fr

In [64]:
pd.Series(d)

key                   sudh
title                kumar
mail     aymane1000live.fr
dtype: object

In [66]:
arr =np.random.randn(3,4)

In [67]:
pd.Series(arr)

ValueError: Data must be 1-dimensional

In [69]:
ser = pd.Series(np.array([2,3,4,5,76]),index= [45,56,7,88,88])

In [70]:
ser

45     2
56     3
7      4
88     5
88    76
dtype: int32

In [74]:
ser.iloc[56] #iloc takes default indexes not given ones

IndexError: single positional indexer is out-of-bounds

In [73]:
ser.loc[56] 

3

In [78]:
np.random.randint(3,6,(4,5))

array([[4, 5, 5, 3, 5],
       [3, 4, 5, 4, 3],
       [4, 5, 3, 4, 4],
       [4, 3, 3, 3, 3]])

In [81]:
pd.DataFrame(np.random.randint(3,6,(4,5)),index = ['a','b','c','d'],columns=['x','y','z','u','v'])

x  y  z  u  v
a  5  5  4  4  4
b  5  3  5  3  5
c  4  5  3  3  3
d  4  5  3  3  5

In [82]:
df = pd.DataFrame(np.random.randint(3,6,(4,5)),index = ['a','b','c','d'],columns=['x','y','z','u','v'])

In [83]:
df.loc[['c','d'],['z','u']]

z  u
c  5  4
d  4  5

In [84]:
df['new'] = df['x'] + df.y

In [85]:
df

x  y  z  u  v  new
a  5  3  4  3  5    8
b  3  3  5  5  4    6
c  3  5  5  4  4    8
d  3  5  4  5  5    8

In [87]:
df.drop('x',axis = 1)

y  z  u  v  new
a  3  4  3  5    8
b  3  5  5  4    6
c  5  5  4  4    8
d  5  4  5  5    8

In [88]:
df.drop('a')

x  y  z  u  v  new
b  3  3  5  5  4    6
c  3  5  5  4  4    8
d  3  5  4  5  5    8

In [89]:
df

x  y  z  u  v  new
a  5  3  4  3  5    8
b  3  3  5  5  4    6
c  3  5  5  4  4    8
d  3  5  4  5  5    8

In [91]:
np.random.rand(4,5)

array([[0.72307731, 0.55680172, 0.42032375, 0.28222777, 0.38260355],
       [0.27264345, 0.69175933, 0.61115919, 0.16088933, 0.72209582],
       [0.12643053, 0.16016245, 0.17335588, 0.14109624, 0.2566616 ],
       [0.22153841, 0.85469398, 0.95127842, 0.497469  , 0.3729679 ]])

In [97]:
np.random.seed(23)
data = pd.DataFrame(np.random.randn(4,5),index = ['a','b','c','d'],columns=['x','y','z','u','v'])

In [99]:
data.values[data.values <0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [107]:
np.where(data.values[data.values <0])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [101]:
rows = np.where(data.values[data.values <0])

In [103]:
type(rows)

tuple

In [105]:
rows[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [110]:
for i in df.columns:
    
    for j in df.index:
        
        if df.loc[j,i]<0:
            
            print(i,j,df.loc[j,i])

In [116]:
d = {'key1':[1,2,3,4,np.nan],"key2":["sudh","kumar",np.nan,3,6],'key3':[np.nan,np.nan,np.nan,3,8]}
df = pd.DataFrame(d)
     

In [117]:
df

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0    NaN   NaN
3   4.0      3   3.0
4   NaN      6   8.0

In [118]:
df.dropna()

key1 key2  key3
3   4.0    3   3.0

In [119]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [120]:
df.dropna(thresh=1)

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0    NaN   NaN
3   4.0      3   3.0
4   NaN      6   8.0

In [121]:
df.dropna(thresh=2)

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
3   4.0      3   3.0
4   NaN      6   8.0

In [123]:
df.dropna(thresh=3)

key1 key2  key3
3   4.0    3   3.0

In [122]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [key1, key2, key3]
Index: []

In [124]:
df.dropna(axis = 1,thresh=2)

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0    NaN   NaN
3   4.0      3   3.0
4   NaN      6   8.0

In [125]:
df.fillna(567)

key1   key2   key3
0    1.0   sudh  567.0
1    2.0  kumar  567.0
2    3.0    567  567.0
3    4.0      3    3.0
4  567.0      6    8.0

In [126]:
df.fillna(value=df['key1'].mean())

key1   key2  key3
0   1.0   sudh   2.5
1   2.0  kumar   2.5
2   3.0    2.5   2.5
3   4.0      3   3.0
4   2.5      6   8.0

In [127]:
df

key1   key2  key3
0   1.0   sudh   NaN
1   2.0  kumar   NaN
2   3.0    NaN   NaN
3   4.0      3   3.0
4   NaN      6   8.0

In [128]:
df.fillna(value=df['key3'].mean())

key1   key2  key3
0   1.0   sudh   5.5
1   2.0  kumar   5.5
2   3.0    5.5   5.5
3   4.0      3   3.0
4   5.5      6   8.0

In [ ]:
dic1 = {'key1':[1,2,3,4,np.nan,"aymane1000@live.fr"],"key2":["sudh","kumar",np.nan,3,6,"xyz@gmail.com"],'key3':[np.nan,np.nan,np.nan,3,8]}
df1 = pd.DataFrame()

In [129]:
d1 = {'name':['sudh','visal','unmag','vishal','aymane'],"mail_id":["sudh@live.fr","visal@live.fr","unmag@live.fr","vishal@live.fr","aymane@live.fr"],'salary':[100,200,3344,555,5567]}

In [130]:
d2=pd.DataFrame(d1)

In [131]:
d2

name         mail_id  salary
0    sudh    sudh@live.fr     100
1   visal   visal@live.fr     200
2   unmag   unmag@live.fr    3344
3  vishal  vishal@live.fr     555
4  aymane  aymane@live.fr    5567

In [133]:
d2.groupby('name').mean()

salary
name          
aymane    5567
sudh       100
unmag     3344
visal      200
vishal     555

In [134]:
d2.groupby('mail_id').mean()

salary
mail_id               
aymane@live.fr    5567
sudh@live.fr       100
unmag@live.fr     3344
visal@live.fr      200
vishal@live.fr     555

In [135]:
d2.groupby('mail_id').sum()

salary
mail_id               
aymane@live.fr    5567
sudh@live.fr       100
unmag@live.fr     3344
visal@live.fr      200
vishal@live.fr     555

In [138]:
d2.groupby('mail_id').describe().iloc[2:3:]

salary                                                    
               count    mean std     min     25%     50%     75%     max
mail_id                                                                 
unmag@live.fr    1.0  3344.0 NaN  3344.0  3344.0  3344.0  3344.0  3344.0

In [142]:
d2.groupby('mail_id').describe().loc['unmag@live.fr']['salary']['mean']

3344.0

In [144]:
d2.groupby('mail_id').describe().T

mail_id       aymane@live.fr  sudh@live.fr  unmag@live.fr  visal@live.fr  \
salary count             1.0           1.0            1.0            1.0   
       mean           5567.0         100.0         3344.0          200.0   
       std               NaN           NaN            NaN            NaN   
       min            5567.0         100.0         3344.0          200.0   
       25%            5567.0         100.0         3344.0          200.0   
       50%            5567.0         100.0         3344.0          200.0   
       75%            5567.0         100.0         3344.0          200.0   
       max            5567.0         100.0         3344.0          200.0   

mail_id       vishal@live.fr  
salary count             1.0  
       mean            555.0  
       std               NaN  
       min             555.0  
       25%             555.0  
       50%             555.0  
       75%             555.0  
       max             555.0

In [145]:
np.random.randn(3,4)

array([[-0.20184052,  1.04537128,  0.53816197,  0.81211867],
       [ 0.2411063 , -0.95250953, -0.13626676,  1.26724821],
       [ 0.17363364, -1.22325477,  1.41531998,  0.45771098]])

In [146]:
arr1 = np.random.randn(3,4)

In [147]:
arr2 = np.random.randn(3,4)

In [148]:
arr3 = np.random.randn(3,4)

In [149]:
pd.DataFrame(arr1,columns=["A","B","C","D"],index=[0,1,2])

0         1         2         3
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620

In [150]:
df1 = pd.DataFrame(arr1,columns=["A","B","C","D"],index=[0,1,2])

In [168]:
df2 = pd.DataFrame(arr2,columns=["A","B","C","D"],index=[3,4,5])

In [153]:
df2

A         B         C         D
0 -0.071324 -0.045438  1.040886 -0.094035
1 -0.420844 -0.551989 -0.121098  0.190141
2  0.512137  0.131538 -0.331617 -1.632386

In [169]:
df3 = pd.DataFrame(arr3,columns=["A","B","C","D"],index=[6,7,8])

In [155]:
df3

A         B         C         D
0  0.619114 -0.992574 -0.161346  1.192404
1  0.250737 -0.813616  0.703624 -0.268142
2 -0.482559  1.244610  0.676860  3.187503

In [156]:
df2

A         B         C         D
0 -0.071324 -0.045438  1.040886 -0.094035
1 -0.420844 -0.551989 -0.121098  0.190141
2  0.512137  0.131538 -0.331617 -1.632386

In [157]:
df1

A         B         C         D
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620

In [158]:
pd.concat([df1,df2,df3])

A         B         C         D
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620
0 -0.071324 -0.045438  1.040886 -0.094035
1 -0.420844 -0.551989 -0.121098  0.190141
2  0.512137  0.131538 -0.331617 -1.632386
0  0.619114 -0.992574 -0.161346  1.192404
1  0.250737 -0.813616  0.703624 -0.268142
2 -0.482559  1.244610  0.676860  3.187503

In [159]:
pd.concat([df1,df2,df3],axis=1)

A         B         C         D         A         B         C  \
0  0.728876  1.968435 -0.547788 -0.679418 -0.071324 -0.045438  1.040886   
1 -2.506230  0.146960  0.606195 -0.022539 -0.420844 -0.551989 -0.121098   
2  0.013422  0.935945  0.420623  0.411620  0.512137  0.131538 -0.331617   

          D         A         B         C         D  
0 -0.094035  0.619114 -0.992574 -0.161346  1.192404  
1  0.190141  0.250737 -0.813616  0.703624 -0.268142  
2 -1.632386 -0.482559  1.244610  0.676860  3.187503

In [160]:
df4 = pd.concat([df1,df2,df3])

In [165]:
df4.iloc[0]

A    0.728876
B    1.968435
C   -0.547788
D   -0.679418
Name: 0, dtype: float64

In [166]:
df5=pd.concat([df1,df2,df3],axis=1)

In [167]:
df5['A']

A         A         A
0  0.728876 -0.071324  0.619114
1 -2.506230 -0.420844  0.250737
2  0.013422  0.512137 -0.482559

In [172]:
pd.concat([df1,df2,df3],axis=1)

A         B         C         D         A         B         C  \
0  0.728876  1.968435 -0.547788 -0.679418       NaN       NaN       NaN   
1 -2.506230  0.146960  0.606195 -0.022539       NaN       NaN       NaN   
2  0.013422  0.935945  0.420623  0.411620       NaN       NaN       NaN   
3       NaN       NaN       NaN       NaN -0.071324 -0.045438  1.040886   
4       NaN       NaN       NaN       NaN -0.420844 -0.551989 -0.121098   
5       NaN       NaN       NaN       NaN  0.512137  0.131538 -0.331617   
6       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
7       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
8       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

          D         A         B         C         D  
0       NaN       NaN       NaN       NaN       NaN  
1       NaN       NaN       NaN       NaN       NaN  
2       NaN       NaN       NaN       NaN       NaN  
3 -0.094035       NaN       NaN       NaN       NaN  
4  0.190141       NaN       NaN       NaN       NaN  
5 -1.632386       NaN       NaN       NaN       NaN  
6       NaN  0.619114 -0.992574 -0.161346  1.192404  
7       NaN  0.250737 -0.813616  0.703624 -0.268142  
8       NaN -0.482559  1.244610  0.676860  3.187503

In [171]:
pd.concat([df1,df2,df3]).T

0         1         2         3         4         5         6  \
A  0.728876 -2.506230  0.013422 -0.071324 -0.420844  0.512137  0.619114   
B  1.968435  0.146960  0.935945 -0.045438 -0.551989  0.131538 -0.992574   
C -0.547788  0.606195  0.420623  1.040886 -0.121098 -0.331617 -0.161346   
D -0.679418 -0.022539  0.411620 -0.094035  0.190141 -1.632386  1.192404   

          7         8  
A  0.250737 -0.482559  
B -0.813616  1.244610  
C  0.703624  0.676860  
D -0.268142  3.187503

In [173]:
pd.concat([df1,df2,df3],axis=1).fillna(0)

A         B         C         D         A         B         C  \
0  0.728876  1.968435 -0.547788 -0.679418  0.000000  0.000000  0.000000   
1 -2.506230  0.146960  0.606195 -0.022539  0.000000  0.000000  0.000000   
2  0.013422  0.935945  0.420623  0.411620  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000 -0.071324 -0.045438  1.040886   
4  0.000000  0.000000  0.000000  0.000000 -0.420844 -0.551989 -0.121098   
5  0.000000  0.000000  0.000000  0.000000  0.512137  0.131538 -0.331617   
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          D         A         B         C         D  
0  0.000000  0.000000  0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000  0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  
3 -0.094035  0.000000  0.000000  0.000000  0.000000  
4  0.190141  0.000000  0.000000  0.000000  0.000000  
5 -1.632386  0.000000  0.000000  0.000000  0.000000  
6  0.000000  0.619114 -0.992574 -0.161346  1.192404  
7  0.000000  0.250737 -0.813616  0.703624 -0.268142  
8  0.000000 -0.482559  1.244610  0.676860  3.187503

In [174]:
df1

A         B         C         D
0  0.728876  1.968435 -0.547788 -0.679418
1 -2.506230  0.146960  0.606195 -0.022539
2  0.013422  0.935945  0.420623  0.411620

In [175]:
df2

A         B         C         D
3 -0.071324 -0.045438  1.040886 -0.094035
4 -0.420844 -0.551989 -0.121098  0.190141
5  0.512137  0.131538 -0.331617 -1.632386

In [176]:
np.random.seed(23)
arr1= np.random.randn(3,4)
np.random.seed(23)
arr2= np.random.randn(3,4)
df11 = pd.DataFrame(arr1,columns=["A","B","C","D"],index=[0,1,2])
df22 = pd.DataFrame(arr2,columns=["A","B","C","D"],index=[3,4,5])

In [178]:
pd.merge(df11,df22,on='A')

A       B_x       C_x       D_x       B_y       C_y       D_y
0  0.666988  0.025813 -0.777619  0.948634  0.025813 -0.777619  0.948634
1  0.701672 -1.051082 -0.367548 -1.137460 -1.051082 -0.367548 -1.137460
2 -1.322148  1.772258 -0.347459  0.670140  1.772258 -0.347459  0.670140

In [179]:
df1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'], 'key2': ['K0', 'K1', 'K0', 'K1'], 'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']})
df2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'], 'key2': ['K0', 'K0', 'K0', 'K0'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']})


In [180]:
pd.merge(df1,df2,on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [181]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']}, index=['K0', 'K1', 'K2']) 
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'], 'D': ['D0', 'D2', 'D3']}, index=['K0', 'K2', 'K3'])


In [183]:
right.join(left,how='right')

C    D   A   B
K0   C0   D0  A0  B0
K1  NaN  NaN  A1  B1
K2   C2   D2  A2  B2