In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import  Ridge,Lasso,RidgeCV,LarsCV

In [2]:
from sklearn.linear_model import  Ridge,Lasso,RidgeCV,LassoCV, ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv('Admission_Prediction.csv')

In [4]:
df.head()

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0           1      337.0        118.0  ...  9.65         1             0.92
1           2      324.0        107.0  ...  8.87         1             0.76
2           3        NaN        104.0  ...  8.00         1             0.72
3           4      322.0        110.0  ...  8.67         1             0.80
4           5      314.0        103.0  ...  8.21         0             0.65

[5 rows x 9 columns]

# Initial analysis of the data 

In [5]:
!pip install pandas-profiling

In [6]:
from pandas_profiling import ProfileReport

In [7]:
ProfileReport(df)

/usr/local/lib/python3.7/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


In [8]:
! pip install pandas==0.25

In [11]:
df

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1      337.0        118.0  ...  9.65         1             0.92
1             2      324.0        107.0  ...  8.87         1             0.76
2             3        NaN        104.0  ...  8.00         1             0.72
3             4      322.0        110.0  ...  8.67         1             0.80
4             5      314.0        103.0  ...  8.21         0             0.65
..          ...        ...          ...  ...   ...       ...              ...
495         496      332.0        108.0  ...  9.02         1             0.87
496         497      337.0        117.0  ...  9.87         1             0.96
497         498      330.0        120.0  ...  9.56         1             0.93
498         499      312.0        103.0  ...  8.43         0             0.73
499         500      327.0        113.0  ...  9.04         0             0.84

[500 rows x 9 columns]

In [12]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [13]:
df['TOEFL Score'] = df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [14]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [16]:
df.describe()

Serial No.   GRE Score  ...    Research  Chance of Admit
count  500.000000  500.000000  ...  500.000000        500.00000
mean   250.500000  316.558763  ...    0.560000          0.72174
std    144.481833   11.103952  ...    0.496884          0.14114
min      1.000000  290.000000  ...    0.000000          0.34000
25%    125.750000  309.000000  ...    0.000000          0.63000
50%    250.500000  316.558763  ...    1.000000          0.72000
75%    375.250000  324.000000  ...    1.000000          0.82000
max    500.000000  340.000000  ...    1.000000          0.97000

[8 rows x 9 columns]

In [17]:
df.isnull().sum() ##No missing values

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [20]:
##Drop serial number
df.drop(columns=['Serial No.'])

GRE Score  TOEFL Score  ...  Research  Chance of Admit
0    337.000000        118.0  ...         1             0.92
1    324.000000        107.0  ...         1             0.76
2    316.558763        104.0  ...         1             0.72
3    322.000000        110.0  ...         1             0.80
4    314.000000        103.0  ...         0             0.65
..          ...          ...  ...       ...              ...
495  332.000000        108.0  ...         1             0.87
496  337.000000        117.0  ...         1             0.96
497  330.000000        120.0  ...         1             0.93
498  312.000000        103.0  ...         0             0.73
499  327.000000        113.0  ...         0             0.84

[500 rows x 8 columns]

In [21]:
#Create x,y columns
x = df.drop(columns=['Chance of Admit'])
y = df['Chance of Admit']

In [23]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [24]:
##DO scalar transform
scalar = StandardScaler()

In [26]:
arr = scalar.fit_transform(x)

In [28]:
df1 = pd.DataFrame(arr)

In [29]:
ProfileReport(df1)

/usr/local/lib/python3.7/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


In [30]:
df1.describe()

0             1  ...             6             7
count  5.000000e+02  5.000000e+02  ...  5.000000e+02  5.000000e+02
mean  -9.059420e-17  4.350520e-15  ...  3.091971e-15 -2.202682e-16
std    1.001002e+00  1.001002e+00  ...  1.001002e+00  1.001002e+00
min   -1.728590e+00 -2.394225e+00  ... -2.940115e+00 -1.128152e+00
25%   -8.642951e-01 -6.814090e-01  ... -7.430227e-01 -1.128152e+00
50%    0.000000e+00  5.124333e-15  ... -2.720919e-02  8.864053e-01
75%    8.642951e-01  6.708143e-01  ...  7.672196e-01  8.864053e-01
max    1.728590e+00  2.113186e+00  ...  2.223672e+00  8.864053e-01

[8 rows x 8 columns]

In [35]:
 #Check multicolinearity either pearson plot of VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df = pd.DataFrame()

In [34]:
[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

[1.0546160412729173,
 4.154481749648817,
 3.8360425383780026,
 2.5174891487426505,
 2.83976843799511,
 2.0574039383600193,
 4.6641838980236425,
 1.4635167717097595]

In [36]:
vif_df['vif'] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [38]:
vif_df['feature'] = x.columns

In [40]:
vif_df ###vif score is lesser than 10 ---> so no need to drop any column

vif            feature
0  1.054616         Serial No.
1  4.154482          GRE Score
2  3.836043        TOEFL Score
3  2.517489  University Rating
4  2.839768                SOP
5  2.057404                LOR
6  4.664184               CGPA
7  1.463517           Research

In [41]:
arr

array([[-1.72859016e+00,  1.84274116e+00,  1.78854223e+00, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [-1.72166195e+00,  6.70814288e-01, -3.10581135e-02, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [-1.71473373e+00,  5.12433309e-15, -5.27312752e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.71473373e+00,  1.21170361e+00,  2.11937866e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [ 1.72166195e+00, -4.10964364e-01, -6.92730965e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 1.72859016e+00,  9.41258951e-01,  9.61451165e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [49]:
#train-test split
x_train, x_test,y_train,y_test = train_test_split(arr,y,test_size= 0.25,random_state=345)

In [51]:
x_train

array([[ 1.72166195, -0.41096436, -0.69273097, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 1.68009264, -1.67303946, -1.02356739, ...,  1.09894429,
        -1.46711143,  0.88640526],
       [ 0.4053007 , -0.41096436,  0.1343601 , ..., -0.52351283,
        -0.07686099, -1.12815215],
       ...,
       [-1.15354814,  0.49051785,  1.29228759, ...,  1.09894429,
         1.29683885,  0.88640526],
       [ 1.48610257, -1.67303946, -1.68524024, ..., -0.52351283,
        -2.26154025, -1.12815215],
       [-1.56231295,  1.75259294,  1.95396044, ...,  0.01730621,
         2.02506527,  0.88640526]])

In [52]:
#Build a model
lr = LinearRegression()

In [53]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [55]:
#Save the model
import pickle
pickle.dump(lr,open("admission_lr_model.pickle",'wb'))

In [56]:
!dir

admission_lr_model.pickle  Admission_Prediction.csv  sample_data


In [61]:
lr.predict([[500, 327.000000,113.000000,4.000000,4.5, 4.5, 9.04, 0]])

array([14.66894563])

In [74]:
#we need to scale the testing iput
test1 =scalar.fit_transform([[25, 336.000000,119.000000 ,5.000000 ,4.0 ,	3.5 ,	9.80,1]])

In [75]:
lr.predict(test1)

array([0.72097959])

In [78]:
#check the score --> Give an unknown dataset
lr.score(x_test,y_test)  

0.7642738167419151

In [79]:
#adjusted r square
def adj_r2(x,y):
  r2 = lr.score(x,y)
  n = x.shape[0]
  p = x.shape[1]
  adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
  return adjusted_r2

In [80]:
adj_r2(x_test,y_test)

0.7480168385861851

In [81]:
lr.coef_

array([0.00961699, 0.02019478, 0.01549054, 0.00805097, 0.00674907,
       0.01509706, 0.07243772, 0.01259734])

In [82]:
lr.intercept_

0.7209795918460346

In [91]:
lassocv = LassoCV(alphas = None,cv=5,max_iter=2000000,normalize=True)
lassocv.fit(x_train,y_train)

LassoCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
        max_iter=2000000, n_alphas=100, n_jobs=None, normalize=True,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [92]:
lassocv.alpha_

6.608444189659907e-06

In [93]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=6.608444189659907e-06, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [94]:
lasso.score(x_test,y_test)

0.7642783141349097

In [104]:
ridge_cv = RidgeCV(alphas=None,cv=10,normalize=True)